In [1]:
#Q1
"""A python library is a collection of functions containg different types of functions. For Eg- Numpy, Pandas, Seaborn, etc."""

'A python library is a collection of functions containg different types of functions. For Eg- Numpy, Pandas, Seaborn, etc.'

In [2]:
#Q2
"""Numpy and array are more or less a similar thing. When we import numpy, we need to convert the list used to array using functions present in numpy.
We use array in case of numpy as arrays are faster. An array is a static variable whereas a list is a dynamic variable"""

'Numpy and array are more or less a similar thing. When we import numpy, we need to convert the list used to array using functions present in numpy. \nWe use array in case of numpy as arrays are faster. An array is a static variable whereas a list is a dynamic variable'

In [10]:
#Q3
import numpy as np
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr.shape

(3, 4)

In [11]:
arr.size

12

In [12]:
arr.ndim

2

In [13]:
#Q4
arr[0]

array([1, 2, 3, 4])

In [17]:
#Q5
arr[2,3]

12

In [18]:
#Q6
arr[arr%2!=0]

array([ 1,  3,  5,  7,  9, 11])

In [20]:
#Q7
np.random.randint(0,2,size=(3,3))

array([[1, 0, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [22]:
#Q8
"""The difference between np.random.rand and np.random.randn is that randn gives random array with normal distribution whereas rand gives array with normal distribution."""

'The difference between np.random.rand and np.random.randn is that randn gives random array with normal distribution whereas rand gives array with normal distribution.'

In [23]:
#Q9
np.expand_dims(arr,axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [24]:
#Q10
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [28]:
#Q11
Mat_A= np.asarray([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
Mat_B= np.asarray([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
Mat_A*Mat_B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [31]:
Mat_A+Mat_B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [32]:
Mat_A-Mat_B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [33]:
Mat_A/Mat_B

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
Mat_A.T@Mat_B

array([[107, 122, 137, 152],
       [122, 140, 158, 176],
       [137, 158, 179, 200],
       [152, 176, 200, 224]])

In [ ]:
#Q12

In [36]:
#Q13

In [40]:
#Q14
"""np.reshape function is used to change the arrangement of matrix by keeping the number of elements same in the matrix"""

'np.reshape function is used to change the arrangement of matrix by keeping the number of elements same in the matrix'

In [39]:
#Q15
"""Broadcasting is basically when internally code streches on of the arrays in order to perform a specific operation over a matrix. Example is shown below"""
arr+np.array([1,2,3,4])
#so, in this example, [1,2,3,4] was broadcasted 4 times so that we can get result.

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])